sp64sqconf= {}
sp64sqconf.cvsw=64
sp64sqconf.cvsh=64
sp64sqconf.template='template/sp64sq/template.png'
--64sqconf.uiw=1920
sp64sqconf.uih=sp64sqconf.cvsh--TODO this should be determined in hduizoom to have button sticking to the righ
sp64sqconf.key='sp64sq'
-- prjfld="project/sd/"
--brshradius=8
prjTemplates['sp64sq']=sp64sqconf